openapi: 3.0.0
info:
  title: Sample User Api
  description: Basic CRUD operations for User management.
  version: 0.0.1
servers:
  - url: 'http://api.example.com/v1'
    description: 'Optional server description, e.g. Main (production) server'
paths:
  allOf:
    - $ref: './endpoints/users.yaml#/users'

components:
  schemas:
    User:
      $ref: './schemas/user.yaml#/User'

securityDefinitions:
  BearerAuth:
    description: |
      Bearer: xxxxxx.yyyyyyy.zzzzzz
    type: apiKey
    in: header
    name: Authorization


security:
  - BearerAuth: []
